.TH "AbstractBullet" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractBullet \- Class to hold information that the other bullets share\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <AbstractBullet\&.h>\fP
.PP
Inherits \fBEntity\fP\&.
.PP
Inherited by \fBBossBullet\fP, \fBCharacterBullet\fP, and \fBObstacleBullet\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBBulletType\fP { \fBPlayer\fP, \fBEnemy\fP, \fBMissile\fP, \fBzBullet\fP, \fBxBulletL\fP, \fBxBulletR\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractBullet\fP ()"
.br
.ti -1c
.RI "bool \fBisHit\fP ()"
.br
.RI "Returns whether the bullet is dead or not\&. "
.ti -1c
.RI "void \fBtranslate\fP (float)"
.br
.RI "Move a certain amount on the Z axis\&. "
.in -1c

Public Member Functions inherited from \fBEntity\fP
.in +1c
.ti -1c
.RI "\fBEntity\fP ()"
.br
.RI "Setup \fBEntity\fP class variables\&. "
.ti -1c
.RI "virtual \fB~Entity\fP ()=0"
.br
.RI "Clean up memory related to \fBEntity\fP class\&. "
.ti -1c
.RI "virtual void \fBkill\fP (\fBAnimation::Anim\fP \fBanimation\fP=\fBAnimation::CHARACTER_DEATH\fP)"
.br
.RI "Run death animation code for the killed entity\&. "
.ti -1c
.RI "virtual void \fBupdate\fP (sf::RenderWindow &, float)=0"
.br
.ti -1c
.RI "int \fBgetAnimationState\fP ()"
.br
.ti -1c
.RI "void \fBsetPos\fP (sf::Vector3f pos)"
.br
.ti -1c
.RI "sf::Vector3f \fBgetPos\fP ()"
.br
.ti -1c
.RI "sf::FloatRect \fBgetBounds\fP ()"
.br
.ti -1c
.RI "sf::Vector2f \fBgetSpritePos\fP ()"
.br
.RI "Get the position of the related sprite for this entity\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBalive\fP = true"
.br
.in -1c

Protected Attributes inherited from \fBEntity\fP
.in +1c
.ti -1c
.RI "sf::Texture * \fBspriteSheet\fP"
.br
.ti -1c
.RI "sf::Sprite * \fBsprite\fP"
.br
.ti -1c
.RI "\fBAnimation\fP \fBanimations\fP"
.br
.ti -1c
.RI "bool \fBdead\fP = false"
.br
.ti -1c
.RI "sf::Text \fBdebugText\fP"
.br
.ti -1c
.RI "sf::Font \fBdebugFont\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to hold information that the other bullets share\&. 
.PP
Definition at line \fB8\fP of file \fBAbstractBullet\&.h\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBAbstractBullet::BulletType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPlayer \fP\fP
.TP
\fB\fIEnemy \fP\fP
.TP
\fB\fIMissile \fP\fP
.TP
\fB\fIzBullet \fP\fP
.TP
\fB\fIxBulletL \fP\fP
.TP
\fB\fIxBulletR \fP\fP
.PP
Definition at line \fB11\fP of file \fBAbstractBullet\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AbstractBullet::AbstractBullet ()\fR [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBAbstractBullet\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool AbstractBullet::isHit ()"

.PP
Returns whether the bullet is dead or not\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB8\fP of file \fBAbstractBullet\&.cpp\fP\&.
.SS "void AbstractBullet::translate (float movement)"

.PP
Move a certain amount on the Z axis\&. 
.PP
\fBParameters\fP
.RS 4
\fImovement\fP 
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBAbstractBullet\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool AbstractBullet::alive = true\fR [protected]\fP"

.PP
Definition at line \fB26\fP of file \fBAbstractBullet\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
