.TH "src/Animation/Animation.cpp" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Animation/Animation.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Animation\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(Animation::* \fBanimation\fP) (sf::Sprite *)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(Animation::* animation) (sf::Sprite *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
