.TH "src/Animation/Animation.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Animation/Animation.h
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnimation\fP"
.br
.RI "Class to handle (almost) all in-game animations\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
