.TH "C:/Zaxxon/src/Background/Background.cpp" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/Background/Background.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Background\&.h'\fP
.br
\fR#include 'Util/Util\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
