.TH "src/Background/Background.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Background/Background.h
.SH SYNOPSIS
.br
.PP
\fR#include <queue>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include 'Entity/Character/Player/Player\&.h'\fP
.br
\fR#include 'Entity/Character/Enemy/Enemy\&.h'\fP
.br
\fR#include 'Obstacle/Obstacle\&.h'\fP
.br
\fR#include 'Wall/Wall\&.h'\fP
.br
\fR#include 'ZapWalls/ZapWalls\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBackground\fP"
.br
.RI "Holds all backgrounds and methods to fill each level with content\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
