.TH "C:/Zaxxon/src/Entity/Character Directory Reference" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/Entity/Character Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEnemy\fP"
.br
.ti -1c
.RI "directory \fBPlayer\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCharacter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCharacter\&.h\fP"
.br
.in -1c
