.TH "C:/Zaxxon/src Directory Reference" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAnimation\fP"
.br
.ti -1c
.RI "directory \fBBackground\fP"
.br
.ti -1c
.RI "directory \fBEntity\fP"
.br
.ti -1c
.RI "directory \fBGame\fP"
.br
.ti -1c
.RI "directory \fBGUI\fP"
.br
.ti -1c
.RI "directory \fBObstacle\fP"
.br
.ti -1c
.RI "directory \fBUtil\fP"
.br
.ti -1c
.RI "directory \fBWall\fP"
.br
.ti -1c
.RI "directory \fBZapWall\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBZaxxon\&.cpp\fP"
.br
.in -1c
