.TH "C:/Zaxxon/src/Entity/Character/Character.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/Entity/Character/Character.h
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include 'Util/Util\&.h'\fP
.br
\fR#include 'Animation/Animation\&.h'\fP
.br
\fR#include 'Entity/Entity\&.h'\fP
.br
\fR#include 'Entity/AbstractBullet/CharacterBullet/CharacterBullet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCharacter\fP"
.br
.RI "Abstract class to hold information that both player and enemy use\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
