.TH "C:/Zaxxon/src/Entity/AbstractBullet/CharacterBullet/CharacterBullet.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/Entity/AbstractBullet/CharacterBullet/CharacterBullet.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./AbstractBullet\&.h'\fP
.br
\fR#include 'Util/Util\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCharacterBullet\fP"
.br
.RI "The bullet used by the player and enemies\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
