.TH "C:/Zaxxon/src/Entity/Character/Enemy/Enemy.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/Entity/Character/Enemy/Enemy.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Character\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemy\fP"
.br
.RI "\fBEnemy\fP in the game\&. These use a recolored player bullet\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3\&.1415f"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PI   3\&.1415f"

.PP
Definition at line \fB2\fP of file \fBEnemy\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
