.TH "C:/Zaxxon/src/Game/Game.cpp" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/Game/Game.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Game\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr unsigned int \fBstartPos\fP = 0"
.br
.ti -1c
.RI "constexpr \fBBackground::Stage\fP \fBstartStage\fP = \fBBackground::INITIAL\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr unsigned int startPos = 0\fR [constexpr]\fP"

.PP
Definition at line \fB3\fP of file \fBGame\&.cpp\fP\&.
.SS "constexpr \fBBackground::Stage\fP startStage = \fBBackground::INITIAL\fP\fR [constexpr]\fP"

.PP
Definition at line \fB4\fP of file \fBGame\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
