.TH "Game" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game \- The main game and all related classes eventually end up being used here\&. \fBGame\fP loop is in here and is the 'heart' of the whole program\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Game\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGame\fP ()"
.br
.RI "Initialize everything needed for the main game functionality\&. "
.ti -1c
.RI "\fB~Game\fP ()"
.br
.RI "Clean up memory when user is done playing the game\&. "
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "Start the game, main game loop is also managed in here\&. "
.in -1c
.SH "Detailed Description"
.PP 
The main game and all related classes eventually end up being used here\&. \fBGame\fP loop is in here and is the 'heart' of the whole program\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Game::Game ()"

.PP
Initialize everything needed for the main game functionality\&. 
.SS "Game::~Game ()"

.PP
Clean up memory when user is done playing the game\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Game::run ()"

.PP
Start the game, main game loop is also managed in here\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
