.TH "src/Game/Game.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Game/Game.h
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include <SFML/Audio\&.hpp>\fP
.br
\fR#include 'Obstacle/Obstacle\&.h'\fP
.br
\fR#include 'Entity/Entity\&.h'\fP
.br
\fR#include 'Entity/Character/Player/Player\&.h'\fP
.br
\fR#include 'Entity/Character/Enemy/Enemy\&.h'\fP
.br
\fR#include 'GUI/GUI\&.h'\fP
.br
\fR#include 'Wall/Wall\&.h'\fP
.br
\fR#include 'Background/Background\&.h'\fP
.br
\fR#include 'Entity/Boss/Boss\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\fP"
.br
.RI "The main game and all related classes eventually end up being used here\&. \fBGame\fP loop is in here and is the 'heart' of the whole program\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBbyte\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
