.TH "src/Game/Game.cpp" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Game/Game.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Game\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBstartPos\fP = 1600"
.br
.ti -1c
.RI "const \fBBackground::Stage\fP \fBstartStage\fP = \fBBackground::INITIAL\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const unsigned int startPos = 1600"

.SS "const \fBBackground::Stage\fP startStage = \fBBackground::INITIAL\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
