.TH "GUI" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI \- Contains all \fBGUI\fP used in the game, including all text\&. These are simple but can take a lot of space due to how much there is\&. Different GUIs are split into different render functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <GUI\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGUI\fP (sf::Texture *)"
.br
.RI "Initializes the \fBGUI\fP (graphical user interface) "
.ti -1c
.RI "\fB~GUI\fP ()"
.br
.RI "Clear up memory related to the \fBGUI\fP\&. "
.ti -1c
.RI "void \fBrender\fP (sf::RenderWindow &, float, int, int, \fBbyte\fP, \fBbyte\fP)"
.br
.RI "Draw all the \fBGUI\fP to the screen each frame\&. Also run logic for certain interactive \fBGUI\fP elements and update them as needed\&. "
.ti -1c
.RI "void \fBstartRender\fP (sf::RenderWindow &, int)"
.br
.RI "Rendering specifically for the start screen\&. This will include the leaderboard will the top 6 scores and names\&. "
.ti -1c
.RI "void \fBrenderScores\fP (sf::RenderWindow &, int[], std::string[])"
.br
.RI "Prepare the leaderboard scores to be rendered\&. "
.ti -1c
.RI "void \fBrenderEnd\fP (sf::RenderWindow &, \fBbyte\fP=255, \fBbyte\fP=0, const char[3]='   ')"
.br
.RI "Specific \fBGUI\fP that renders once you've run out of lives\&. This includes the game over text and name entry screen\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains all \fBGUI\fP used in the game, including all text\&. These are simple but can take a lot of space due to how much there is\&. Different GUIs are split into different render functions\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GUI::GUI (sf::Texture * spritesheet)"

.PP
Initializes the \fBGUI\fP (graphical user interface) 
.PP
\fBParameters\fP
.RS 4
\fIspritesheet\fP 
.RE
.PP

.SS "GUI::~GUI ()"

.PP
Clear up memory related to the \fBGUI\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "void GUI::render (sf::RenderWindow & window, float playerY, int score, int highScore, \fBbyte\fP fuel, \fBbyte\fP lives)"

.PP
Draw all the \fBGUI\fP to the screen each frame\&. Also run logic for certain interactive \fBGUI\fP elements and update them as needed\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP 
.br
\fIplayerY\fP 
.br
\fIscore\fP 
.br
\fIfuel\fP 
.RE
.PP

.SS "void GUI::renderEnd (sf::RenderWindow & window, \fBbyte\fP timeLeft = \fR255\fP, \fBbyte\fP selector = \fR0\fP, const char name[3] = \fR'   '\fP)"

.PP
Specific \fBGUI\fP that renders once you've run out of lives\&. This includes the game over text and name entry screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP 
.br
\fIstate\fP 
.RE
.PP

.SS "void GUI::renderScores (sf::RenderWindow & window, int scores[], std::string names[])"

.PP
Prepare the leaderboard scores to be rendered\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP 
.br
\fIscores\fP 
.RE
.PP

.SS "void GUI::startRender (sf::RenderWindow & window, int highScore)"

.PP
Rendering specifically for the start screen\&. This will include the leaderboard will the top 6 scores and names\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP 
.br
\fIhighScore\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
