.TH "C:/Zaxxon/src/GUI/GUI.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/GUI/GUI.h
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include 'ZaxxonText/ZaxxonText\&.h'\fP
.br
\fR#include 'HMSection/HMSection\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGUI\fP"
.br
.RI "Contains all \fBGUI\fP used in the game, including all text\&. These are simple but can take a lot of space due to how much there is\&. Different GUIs are split into different render functions\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBbyte\fP = unsigned char"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBbyte\fP = unsigned char"

.PP
Definition at line \fB6\fP of file \fBGUI\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
