.TH "C:/Zaxxon/src/Obstacle/Obstacle.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/Obstacle/Obstacle.h
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'Util/Util\&.h'\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include 'Entity/Entity\&.h'\fP
.br
\fR#include 'Entity/AbstractBullet/ObstacleBullet/ObstacleBullet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBObstacle\fP"
.br
.RI "Still obstacles that spawn across the levels\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
