.TH "src/Entity/Character/Player/Player.cpp" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Entity/Character/Player/Player.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Player\&.h'\fP
.br
\fR#include 'Background/Background\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
