.TH "ZapWalls" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZapWalls \- Class for other walls (blue lightning)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ZapWalls\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZapWalls\fP (sf::Texture *, sf::Vector3f)"
.br
.ti -1c
.RI "\fB~ZapWalls\fP ()"
.br
.ti -1c
.RI "void \fBdrawZapWalls\fP (sf::RenderWindow &)"
.br
.ti -1c
.RI "bool \fBcheckOnScreen\fP ()"
.br
.ti -1c
.RI "sf::Vector3f \fBgetStartPosition\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for other walls (blue lightning)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ZapWalls::ZapWalls (sf::Texture * tex, sf::Vector3f pos)"

.SS "ZapWalls::~ZapWalls ()"

.SH "Member Function Documentation"
.PP 
.SS "bool ZapWalls::checkOnScreen ()"

.SS "void ZapWalls::drawZapWalls (sf::RenderWindow & window)"

.SS "sf::Vector3f ZapWalls::getStartPosition ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
