.TH "C:/Zaxxon/src/ZapWall/ZapWall.h" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/ZapWall/ZapWall.h
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include 'Util/Util\&.h'\fP
.br
\fR#include 'Entity/Entity\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZapWall\fP"
.br
.RI "Class for other walls (blue lightning)\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
