.TH "ZaxxonText" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZaxxonText \- Class to grab text sprites from spritesheet given char or string\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ZaxxonText\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static sf::Sprite \fBget\fP (sf::Texture *, char)"
.br
.RI "Take character or hex value then convert it and return the matching character/symbol from our spritesheet\&. "
.ti -1c
.RI "static void \fBstring\fP (sf::Texture *, std::string, sf::Sprite *)"
.br
.RI "Take a string of characters or hex values then convert all and then fill given sprite array with the matching characters/symbols for each\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class to grab text sprites from spritesheet given char or string\&. 
.SH "Member Function Documentation"
.PP 
.SS "sf::Sprite ZaxxonText::get (sf::Texture * spritemap, char in)\fR [static]\fP"

.PP
Take character or hex value then convert it and return the matching character/symbol from our spritesheet\&. 
.PP
\fBParameters\fP
.RS 4
\fIspritemap\fP 
.br
\fIin\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Sprite of character or symbol
.RE
.PP

.SS "void ZaxxonText::string (sf::Texture * spritemap, std::string in, sf::Sprite * arr)\fR [static]\fP"

.PP
Take a string of characters or hex values then convert all and then fill given sprite array with the matching characters/symbols for each\&. 
.PP
\fBParameters\fP
.RS 4
\fIspritemap\fP 
.br
\fIin\fP 
.br
\fIarr\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
