.TH "C:/Zaxxon/src/Zaxxon.cpp" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Zaxxon/src/Zaxxon.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include 'Game/Game\&.h'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB30\fP of file \fBZaxxon\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
