.TH "src/Zaxxon.cpp" 3 "Version 1.0" "Zaxxon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Zaxxon.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include 'Game/Game\&.h'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <crtdbg\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_CRTDBG_MAP_ALLOC\fP"
.br
.ti -1c
.RI "#define \fBDBG_NEW\fP   new"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _CRTDBG_MAP_ALLOC"

.SS "#define DBG_NEW   new"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zaxxon from the source code\&.
